name: news_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  postor: ^0.0.4+1
  provider: ^6.0.0
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: 1.7.2

flutter:

  uses-material-design: true
